# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.network :private_network, ip: "10.10.10.10"

  config.vm.network :forwarded_port, guest: 80, host: 8000, id: "http", auto_correct: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
  end

end
