# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# This is quite the minimal configuration necessary
# to start an OpenStack instance using Vagrant.
#
# This example assumes a floating IP is needed to
# reach the machine, although you might remove the
# floating_ip_pool parameter if you are able to join
# the instance using its private IP address (e.g.
# through a VPN).
#
Vagrant.configure('2') do |config|

  config.ssh.username = "ubuntu"

  config.vm.provider :openstack do |os, ov|
    os.openstack_auth_url               = ENV['OS_AUTH_URL']
    os.tenant_name                      = ENV['OS_TENANT_NAME']
    os.username                         = ENV['OS_USERNAME']
    os.password                         = ENV['OS_PASSWORD']
    os.region                           = ENV['OS_REGION_NAME']
    os.flavor                           = ENV['OS_FLAVOR']
    ov.vm.allowed_synced_folder_types = :rsync
    ov.nfs.functional = false
  end

  config.vm.define 'am-xenial-deb' do |s|
    s.vm.provider :openstack do |os, override|
      os.image = ENV['OS_IMAGE']
      os.server_name = 'archivematica-xenial-rpm'
    end
  end

  config.vm.provision "shell", path: "https://gist.githubusercontent.com/scollazo/0db94d934c27081cd56a14d2b2a0e4b8/raw/99a5559e1dd70d9b896b24dae733dbb2f4b0e70e/xenial-am18-deb.sh"
end
