---

# archivematica-src role

archivematica_src_am_version: "wip/am-centos8"
archivematica_src_ss_version: "wip/ss-centos8"

archivematica_src_ss_db_name: "SS"
archivematica_src_ss_db_user: "ss"
archivematica_src_ss_db_password: "ChangeMe!n0w"
archivematica_src_ss_db_host: "{{ archivematica_src_am_db_host }}"

archivematica_src_am_db_host: "localhost"        # Archivematica database host
archivematica_src_am_db_name: "MCP"              # Archivematica database name
archivematica_src_am_db_user: "archivematica"    # Archivematica database user
archivematica_src_am_db_password: "ChangeMe!n0w"



archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
archivematica_src_configure_ss_user: "admin"
archivematica_src_configure_ss_password: "archivematica"
archivematica_src_configure_ss_api_key: "this_is_the_ss_api_key"
archivematica_src_configure_ss_url: "http://{{ ansible_host }}:8000"
archivematica_src_configure_ss_email: "admin@example.com"
archivematica_src_configure_am_user: "admin"
archivematica_src_configure_am_password: "archivematica"
archivematica_src_configure_am_email: "admin@example.com"
archivematica_src_configure_am_api_key: "this_is_the_am_api_key"
archivematica_src_configure_am_site_url: "http://{{ ansible_host }}"


#Disable fits:

archivematica_src_configure_fpcommand:
  FITS:
    enabled: '0'
    field_name: 'description'

# 
archivematica_src_configure_fprule:
  c3b06895-ef9d-401e-8c51-ac585f955655: #Fits
    enabled: '0'
    field_name: 'uuid'


# elasticsearch role

elasticsearch_version: "6.5.4"
elasticsearch_java_home: "/usr/lib/jvm/jre-1.8.0"
elasticsearch_heap_size: "1g"
elasticsearch_max_open_files: "65535"
elasticsearch_timezone: "UTC"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "thread_pool.bulk.size: 2"
  - "thread_pool.bulk.queue_size: 1000"
elasticsearch_network_http_max_content_lengtht: 1024mb
elasticsearch_discovery_zen_ping_multicast_enabled: "false"
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_network_host: "127.0.0.1"

# Percona variables
mysql_version_major: "5"
mysql_version_minor: "7"
mysql_optimizer_switch: "'block_nested_loop=off'"
mysql_sql_mode: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
mysql_innodb_log_file_size: "64M"
mysql_innodb_buffer_pool_size: "256M"

mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"
  - name: "{{ archivematica_src_ss_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"
  - name: "{{ archivematica_src_ss_db_user }}"
    pass: "{{ archivematica_src_ss_db_password }}"
    priv: "{{ archivematica_src_ss_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_ss_db_host }}"

mysql_root_password: "ChangeMe!n0w"

archivematica_src_ss_environment:
  SS_DB_URL: "mysql://{{ archivematica_src_ss_db_user }}:{{ archivematica_src_ss_db_password }}@{{ archivematica_src_ss_db_host }}:3306/{{ archivematica_src_ss_db_name }}"
