# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = ENV.fetch("VAGRANT_BOX", "ubuntu/trusty64")

  {
    "am-local" => {
      "ip" => "192.168.168.192",
      "memory" => "2048",
      "cpus" => "2",
    },
  }.each do |short_name, properties|

    # Define guest
    config.vm.define short_name do |host|
      host.vm.network "private_network", ip: properties.fetch("ip")
      host.vm.hostname = "#{short_name}.myapp.dev"
    end

    # Set the amount of RAM and virtual CPUs for the virtual machine
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", properties.fetch("memory")]
      vb.customize ["modifyvm", :id, "--cpus", properties.fetch("cpus")]
    end

  end

  # Make the project root available to the guest VM
  config.vm.synced_folder '.', '/vagrant'

  # Only provision if explicitly request with 'provision' or 'up --provision'
  if ARGV.any? { |arg| arg =~ /^(--)?provision$/ }
    system("ansible-galaxy install -f -r requirements.yml")
    config.vm.provision :ansible do |ansible|
      ansible.inventory_path = "./hosts"
      ansible.playbook = "./singlenode.yml"
    end
  end

end
