---

# archivematica-src role

archivematica_src_install_devtools: "false"
archivematica_src_am_version: "qa/1.x"
archivematica_src_ss_version: "qa/0.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "true"
archivematica_src_sample_data_git_force: "yes"


archivematica_src_rpm_repositories:
  archivematica-storage:
    baseurl: "https://jenkins-ci.archivematica.org/repos/am-packbuild/0.19.0/centos7"
    #gpgkey: "https://packages.archivematica.org/1.13.x/key.asc"
    gpgcheck: 0
  archivematica-dashboard:
    baseurl: "https://jenkins-ci.archivematica.org/repos/am-packbuild/1.14.0/centos7"
    #gpgkey: "https://packages.archivematica.org/1.13.x/key.asc"
    gpgcheck: 0
  archivematica-extras:
    baseurl: "https://packages.archivematica.org/1.13.x/centos-extras"
    gpgkey: "https://packages.archivematica.org/1.13.x/key.asc"
    gpgcheck: 1


archivematica_src_am_db_password: "aaGKHyMls.20ki"
archivematica_src_ss_db_name: "SS"
archivematica_src_ss_db_user: "ss"
archivematica_src_ss_db_password: "aaGKHyMls.20ki$"
archivematica_src_ss_db_host: "{{ archivematica_src_am_db_host }}"

# elasticsearch role

elasticsearch_version: "6.5.4"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
elasticsearch_heap_size: "1g"
elasticsearch_max_open_files: "65535"
elasticsearch_timezone: "UTC"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "thread_pool.write.size: 2"
  - "thread_pool.write.queue_size: 1000"
elasticsearch_network_http_max_content_lengtht: 1024mb
elasticsearch_discovery_zen_ping_multicast_enabled: "false"
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_network_host: "127.0.0.1"

# percona role

mysql_version_major: "8"
mysql_version_minor: "0"

mysql_optimizer_switch: "'block_nested_loop=off'"
mysql_sql_mode: "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
mysql_default_authentication_plugin: "mysql_native_password"

mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8mb4_0900_ai_ci"
    encoding: "utf8mb4"
  - name: "{{ archivematica_src_ss_db_name }}"
    collation: "utf8mb4_0900_ai_ci"
    encoding: "utf8mb4"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"
  - name: "{{ archivematica_src_ss_db_user }}"
    pass: "{{ archivematica_src_ss_db_password }}"
    priv: "{{ archivematica_src_ss_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_ss_db_host }}"

mysql_root_password: "aaGKHyMls.20ki$"

#AM configure vars

archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
archivematica_src_configure_ss_user: "admin"
archivematica_src_configure_ss_password: "archivematica"
archivematica_src_configure_ss_email: "admin@example.com"
archivematica_src_configure_am_user: "admin"
archivematica_src_configure_am_password: "archivematica"
archivematica_src_configure_am_email: "admin@example.com"

archivematica_src_am_mcpserver_environment:
  ARCHIVEMATICA_MCPSERVER_MCPSERVER_CONCURRENT_PACKAGES: 2

archivematica_src_am_mcpclient_environment:
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_METADATA_XML_VALIDATION_ENABLED: "true"
  METADATA_XML_VALIDATION_SETTINGS_FILE: "/home/{{ ansible_user_id }}/archivematica-sampledata/xml-validation/xml_validation.py"
