---

# archivematica-src role

archivematica_src_install_devtools: "yes"
archivematica_src_am_version: "qa/1.x"
archivematica_src_ss_version: "qa/0.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "true"

# new in qa/1.x post 1.7.x 

    # changed from ansible-archivematica-src defaults
archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
#archivematica_src_configure_ss_dashboard: "yes"
archivematica_src_configure_ss_user: "admin"
archivematica_src_configure_ss_password: "nottest"
archivematica_src_configure_ss_email: "test@example.com"
archivematica_src_configure_ss_api_key: "nottest"
archivematica_src_configure_ss_url: "http://iishtall.qa.archivematica.org:8000"
archivematica_src_configure_am_user: "admin"
archivematica_src_configure_am_password: "test"
archivematica_src_configure_am_email: "test@example.com"
archivematica_src_configure_am_api_key: "test"
archivematica_src_configure_am_org_name: "artefactual_test"
archivematica_src_configure_am_org_id: "12345"
archivematica_src_configure_am_whitelist: '"127.0.0.1"'

archivematica_src_mcpclient_clamav_use_tcp: "no"

    # not changes from ansible-archivematica-src defaults
archivematica_src_mcpclient_clamav_tcp_ip: "localhost"
archivematica_src_mcpclient_clamav_tcp_port: "3310"
archivematica_src_install_fixity: "no"
archivematica_src_search_enabled: "yes"

# DJANGO_SECRET_KEY: "12345"
#       DJANGO_SETTINGS_MODULE: "settings.common"
#       ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER: "gearmand:4730"
#        NAILGUN_SERVER: "fits"
#       NAILGUN_PORT: "2113"
#       ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER: "elasticsearch:9200"
# FORWARDED_ALLOW_IPS: "*"
#       AM_GUNICORN_ACCESSLOG: "/dev/null"
#       AM_GUNICORN_RELOAD: "true"
#       AM_GUNICORN_RELOAD_ENGINE: "auto"
#       DJANGO_SETTINGS_MODULE: "settings.local"
#       SS_DB_URL: "mysql://archivematica:demo@mysql/SS"
#       SS_GNUPG_HOME_PATH: "/src/"


# elasticsearch role

elasticsearch_version: "1.7.6"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_java_home: "/usr/lib/jvm/java-8-openjdk-amd64"
elasticsearch_heap_size: "640m"
elasticsearch_max_open_files: "65535"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "threadpool.bulk.type: fixed"
  - "threadpool.bulk.size: 50"
  - "threadpool.bulk.queue_size: 1000"

# percona role

# percona role

mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"


mysql_root_password: "12345"
