# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# This is quite the minimal configuration necessary
# to start an OpenStack instance using Vagrant.
#
# This example assumes a floating IP is needed to
# reach the machine, although you might remove the
# floating_ip_pool parameter if you are able to join
# the instance using its private IP address (e.g.
# through a VPN).
#
Vagrant.configure('2') do |config|

  config.ssh.username = "ubuntu"
  config.vm.provider :openstack do |os, ov|
    os.server_name                      = 'test_xenial'
    os.openstack_auth_url               = ENV['OS_AUTH_URL']
    os.tenant_name                      = ENV['OS_TENANT_NAME']
    os.username                         = ENV['OS_USERNAME']
    os.password                         = ENV['OS_PASSWORD']
    os.region                           = ENV['OS_REGION_NAME']
    os.flavor                           = ENV['OS_FLAVOR']
    os.image                            = "Ubuntu 16.04"
    ov.vm.allowed_synced_folder_types = :rsync
    ov.nfs.functional = false
  end

 
  # Ansible provisioning
  config.vm.provision "shell", inline: "sudo apt-get install -y python"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./singlenode.yml"
    ansible.host_key_checking = false
    ansible.extra_vars = {
      "archivematica_src_dir" => "/vagrant/src/",
      "archivematica_src_environment_type" => "development",
    }
    # Accept multiple arguments, separated by colons
    ansible.raw_arguments = ENV['ANSIBLE_ARGS'].to_s.split(':')
  end

end
