---

# archivematica-src role

archivematica_src_install_devtools: "yes"
archivematica_src_am_version: "stable/1.7.x"
archivematica_src_ss_version: "stable/0.11.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "true"
archivematica_src_dir: "/opt/archivematica"

# elasticsearch role

elasticsearch_version: "1.7.6"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_apt_repos: []
elasticsearch_apt_dependencies: []
elasticsearch_java_home: "/usr/lib/jvm/java-8-openjdk-amd64"
elasticsearch_heap_size: "640m"
elasticsearch_max_open_files: "65535"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "threadpool.bulk.type: fixed"
  - "threadpool.bulk.size: 50"
  - "threadpool.bulk.queue_size: 1000"

# percona role

mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"

mysql_root_password: "ChangeMe!"
