---

# archivematica-src role

archivematica_src_install_devtools: "yes"
archivematica_src_am_version: "qa/1.x"
archivematica_src_ss_version: "qa/0.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "true"

# elasticsearch role

elasticsearch_version: "1.7.6"
elasticsearch_apt_java_package: "oracle-java8-installer"
elasticsearch_java_home: "/usr/lib/jvm/java-8-oracle"
elasticsearch_heap_size: "640m"
elasticsearch_max_open_files: "65535"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "threadpool.bulk.type: fixed"
  - "threadpool.bulk.size: 50"
  - "threadpool.bulk.queue_size: 1000"

# percona role

mysql_root_password: "MYSQLROOTPASSWORD"
