# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder '.', '/vagrant'

  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network :private_network, ip: "192.168.100.50"
    nfs.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
    end
  end

  config.vm.define "es01" do |es01|
    es01.vm.hostname = "es01"
    es01.vm.network :private_network, ip: "192.168.100.100"
    es01.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
    end
  end

  config.vm.define "es02" do |es02|
    es02.vm.hostname = "es02"
    es02.vm.network :private_network, ip: "192.168.100.101"
    es02.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
    end
  end

  config.vm.define "es03" do |es03|
    es03.vm.hostname = "es03"
    es03.vm.network :private_network, ip: "192.168.100.102"
    es03.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.inventory_path = "hosts"
    ansible.playbook = "playbook.yml"
    ansible.host_key_checking = false
    ansible.verbose = "vvvvv"
  end

  # if Vagrant.has_plugin?("vagrant-cachier")
  #   config.cache.scope = :box
  #   config.cache.synced_folder_opts = {
  #     type: :nfs,
  #     mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  #   }
  # end

end
