---
- hosts: "am-local"

  pre_tasks:

    - fail:
        msg: "This playbook is temporarily disabled, see https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/25 for more details."

    - include_vars: "vars-singlenode-qa.yml"
      tags:
        - "always"

    - name: "Install packages for development convenience"
      apt:
        pkg: "{{ item }}"
        state: "latest"
        update_cache: yes
        cache_valid_time: 0
      with_items:
        - "fish"
      become: "yes"

  roles:

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.clamav"
      become: "yes"
      tags:
        - "clamav"

    - role: "artefactual.archivematica-src"
      become: "yes"
      tags:
        - "archivematica-src"
