---

# archivematica-src role

archivematica_src_install_devtools: "yes"
archivematica_src_install_automationtools: "yes"
archivematica_src_am_version: "stable/1.11.x"
archivematica_src_ss_version: "stable/0.16.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "true"


#Automation tools settings:

automationtools_automated_transfer_source_description: "automated workflow"

# elasticsearch role

elasticsearch_version: "6.5.4"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
elasticsearch_heap_size: "1g"
elasticsearch_max_open_files: "65535"
elasticsearch_timezone: "UTC"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "thread_pool.write.size: 2"
  - "thread_pool.write.queue_size: 1000"
elasticsearch_network_http_max_content_lengtht: 1024mb
elasticsearch_discovery_zen_ping_multicast_enabled: "false"
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_network_host: "127.0.0.1"

# percona role

mysql_version_major: "5"
mysql_version_minor: "7"
mysql_optimizer_switch: "'block_nested_loop=off'"
mysql_sql_mode: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
mysql_innodb_log_file_size: "64M"
mysql_innodb_buffer_pool_size: "256M"

mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"
  - name: "{{ nextcloud_db_name }}"
    collation: "utf8mb4_general_ci"
    encoding: "utf8mb4"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"
  - name: "{{ nextcloud_db_admin }}"
    pass: "{{ nextcloud_db_pwd }}"
    priv: "{{ nextcloud_db_name }}.*:ALL,GRANT"
    host: "{{ archivematica_src_am_db_host }}"

mysql_root_password: "MYSQLROOTPASSWORD"

#AM configure vars

archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
archivematica_src_configure_ss_user: "admin"
archivematica_src_configure_ss_password: "archivematica"
archivematica_src_configure_ss_url: "http://192.168.168.198:8000"
archivematica_src_configure_ss_email: "admin@example.com"
archivematica_src_configure_am_user: "admin"
archivematica_src_configure_am_password: "archivematica"
archivematica_src_configure_am_email: "admin@example.com"
archivematica_src_configure_am_site_url: "http://192.168.168.198"

am_ss_default_location_data_transfer_sources:
  - { ts_path: '/home/automated_workflow', ts_description: 'automated workflow', ts_default: 'false' }

#
#  nextcloud role configuration
#

nextcloud_version_channel: "releases"
nextcloud_get_latest: false
nextcloud_version_full: "18.0.2"

#Use vagrantbox IP Address
nextcloud_fqdn_host: "192.168.168.198"

nexcloud_nginx_listen_port: "8888"

nextcloud_websrv_template: "templates/nginx_nc_am.j2"

nextcloud_trusted_domain:
  - "{{ nextcloud_fqdn_host }}"
  - "{{ ansible_default_ipv4.address }}"

nextcloud_mysql_root_pwd: "{{ mysql_root_password }}"
nextcloud_websrv: "nginx"
nextcloud_websrv_user: "www-data"
nextcloud_websrv_group: "www-data"
nextcloud_data_dir: "/opt/ncdata"
nextcloud_admin_name: "admin"
nextcloud_admin_pwd: "archivematica"

nextcloud_background_cron: True

nextcloud_install_redis_server: false
nextcloud_redis_host: '/var/run/redis/redis.sock'
nextcloud_redis_port: 0

nextcloud_redis_settings:
  - { name: 'redis host', value: '"{{ nextcloud_redis_host }}"' }
  - { name: 'redis port', value: "{{ nextcloud_redis_port }}" }

nextcloud_install_tls: false
#nextcloud_tls_cert_method: "installed"
#nextcloud_tls_cert: /var/lib/acme/live/nextcloud.cooperators.archivematica.org/cert
#nextcloud_tls_cert_key: /var/lib/acme/live/nextcloud.cooperators.archivematica.org/privkey

nextcloud_config_settings:
  - { name: 'overwrite.cli.url', value: 'http://{{ nextcloud_trusted_domain | first }}' }
  - { name: 'open_basedir', value: '/dev/urandom' }
  - { name: 'mysql.utf8mb4', value: 'true' }
  - { name: 'updatechecker', value: 'false' } # disable autoupdate
  - { name: 'updater.release.channel', value: 'production' }
  - { name: 'skeletondirectory', value: '' }
  - { name: 'filelocking.ttl', value: 3600 }
  - { name: 'log_type', value: '/var/log/nextcloud.log' }
  - { name: 'logfilemode', value: 416 }
  - { name: 'logdateformat', value: 'F d, Y H:i:s' }

nextcloud_files_external_settings:
  - { name: 'home', value: '/home' }
  - { name: 'nextcloud-TS-dir', value: '/home/nextcloud-TS-dir' }
  - { name: 'automated_workflow', value: '/home/automated_workflow' }
  - { name: 'archivematica-aips', value: '/var/archivematica/sharedDirectory/www/AIPsStore' }
  - { name: 'archivematica-dips', value: '/var/archivematica/sharedDirectory/www/DIPsStore' }
  - { name: 'archivematica-processing-config', value: '/var/archivematica/sharedDirectory/sharedMicroServiceTasksConfigs/processingMCPConfigs' }

nextcloud_add_users:
  - { name: 'archivematica_1', password: '12345', display_name: 'Archivematica user1', group: 'users' }
  - { name: 'archivematica_2', password: '12345', display_name: 'Archivematica user2', group: 'users' }
  - { name: 'archivematica_3', password: '12345', display_name: 'Archivematica user3', group: 'users' }

nexcloud_apps_to_delete:
  - "files_trashbin"
  - "password_policy"

nextcloud_install_db: false
nextcloud_db_backend: "mysql"
nextcloud_db_name: "nextcloud"
nextcloud_db_admin: "ncadmin"
nextcloud_db_pwd: "secret"
