atom_site_backend:
  - upstream {{ site }} {
      server unix:/var/run/php-fpm.{{ site }}.sock;
    }

sslredirect:
  - listen 80
  - server_name {{ server_name|default('_') }} {{ server_alias | default('') }}
  - include /etc/nginx/acmetool-location.conf
  - location / { return 301 https://{{ server_name }}$request_uri; }

atomssl:
  - listen 443
  - '{% if atom_revision_directory|bool %}
    set $atom_path {{ atom_path }}/{{ atom_revision_directory_latest_symlink_dir }}
    {% else %}
    set $atom_path {{ atom_path }}
    {% endif %}'
  - root $atom_path
  - server_name {{ server_name|default('_') }} {{ server_alias | default('') }}
  - ssl on
  - ssl_certificate {{ atom_https_certificate|default('/dev/null') }}
  - ssl_certificate_key {{ atom_https_certificate_key|default('/dev/null') }}
  - ssl_session_timeout 5m
  - ssl_session_cache shared:SSL:50m
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA'
  - ssl_prefer_server_ciphers on
  - client_max_body_size {{ atom_client_max_body_size | default ('100M') }}
  - '{% if http_auth_user is defined %}
    satisfy any;
    # tamias ;
    allow 142.58.233.57;  
    # Artefactual VPN ; 
    allow 104.248.105.95; 
    # Santi ;
    allow	83.165.159.164; 
    # Tessa ;
    allow 192.222.199.217; 
    deny all;
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/auth_basic/htpasswd.{{ site_normalized }}
    {% endif %}'
  - location / { try_files $uri /index.php?$args; }
  - location ~ /\. {
      deny all;
      return 404;
    }
  - location ~* (\.yml|\.ini|\.tmpl)$ {
      deny all;
      return 404;
    }
  - location ~* /(?:uploads|files)/.*\.php$ {
      deny all;
      return 404;
    }
  - location ~* /uploads/r/(.*)/conf/ { }
  - location ~* ^/uploads/r/(.*)$ {
      include /etc/nginx/fastcgi_params;
      set $index /index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$index;
      fastcgi_param SCRIPT_NAME $index;
      fastcgi_pass {{ site }};
    }
  - location ~ ^/private/(.*)$ {
      internal;
      alias $atom_path/$1;
    }
  - location ~ ^/(index|qubit_dev)\.php(/|$) {
      include /etc/nginx/fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_split_path_info ^(.+\.php)(/.*)$;
      fastcgi_pass {{ site }};
    }
  - location ~* \.php$ {
      deny all;
      return 404;
    }


atomnginx:
  - listen 80
  - '{% if atom_revision_directory|bool %}
    set $atom_path {{ atom_path }}/{{ atom_revision_directory_latest_symlink_dir }}
    {% else %}
    set $atom_path {{ atom_path }}
    {% endif %}'
  - root $atom_path
  - server_name {{ server_name|default('_') }} {{ server_alias | default('') }}
  - include /etc/nginx/acmetool-location.conf
  - '{% if http_auth_user is defined %}
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/auth_basic/htpasswd.{{ site_normalized }}
    {% endif %}'
  - client_max_body_size {{ atom_client_max_body_size | default ('100M') }}
  - location / { try_files $uri /index.php?$args; }
  - location ~ /\. {
      deny all;
      return 404;
    }
  - location ~* (\.yml|\.ini|\.tmpl)$ {
      deny all;
      return 404;
    }
  - location ~* /(?:uploads|files)/.*\.php$ {
      deny all;
      return 404;
    }
  - location ~* /uploads/r/(.*)/conf/ { }
  - location ~* ^/uploads/r/(.*)$ {
      include /etc/nginx/fastcgi_params;
      set $index /index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$index;
      fastcgi_param SCRIPT_NAME $index;
      fastcgi_pass {{ site }};
    }
  - location ~ ^/private/(.*)$ {
      internal;
      alias $atom_path/$1;
    }
  - location ~ ^/(index|qubit_dev)\.php(/|$) {
      include /etc/nginx/fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_split_path_info ^(.+\.php)(/.*)$;
      fastcgi_pass {{ site }};
    }
  - location ~* \.php$ {
      deny all;
      return 404;
    }

proxy_ssl:
  - listen 443
  - root /dev/null
  - server_name {{ server_name|default('_') }} {{ server_alias | default('') }}
  - ssl on
  - ssl_certificate {{ atom_https_certificate|default('/dev/null') }}
  - ssl_certificate_key {{ atom_https_certificate_key|default('/dev/null') }}
  - ssl_session_timeout 5m
  - ssl_session_cache shared:SSL:50m
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA'
  - ssl_prefer_server_ciphers on
#  - add_header Strict-Transport-Security max-age=63072000
  - include /etc/nginx/auth_basic/badbots
  - client_max_body_size {{ atom_client_max_body_size | default ('100M') }}
  - location / {
      proxy_pass http://{{ hostvars[host]['ansible_ssh_host'] }};
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 500M;
      proxy_read_timeout 3600; }

proxy_nossl:
  - listen 80
  - root /dev/null
  - server_name {{ server_name }} {{ server_alias | default('') }}
  - include /etc/nginx/auth_basic/badbots
  - client_max_body_size {{ atom_client_max_body_size | default ('100M') }}
  - location / {
      proxy_pass http://{{ hostvars[host]['ansible_ssh_host'] }};
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 500M;
      proxy_read_timeout 3600; }


proxy_sites:
  secure:
    - listen 443
    - root /dev/null
    - server_name {{ server_name }}
    - ssl on
    - ssl_certificate {{ atom_https_certificate|default('/dev/null') }}
    - ssl_certificate_key {{ atom_https_certificate_key|default('/dev/null') }}
    - ssl_session_timeout 5m
    - ssl_session_cache shared:SSL:50m
    - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
    - ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA'
    - ssl_prefer_server_ciphers on
#    - add_header Strict-Transport-Security max-age=63072000
    - include /etc/nginx/auth_basic/badbots
    - location / {
        proxy_pass http://{{ hostvars[host]['ansible_ssh_host'] }};
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 500M;
        proxy_read_timeout 3600; }

nginx_auth_basic_files_frontend:
  badbots:
    - if ($http_user_agent ~* "baidu") { return 403; }
    - if ($http_user_agent ~* "ahrefs") { return 403; }
    - if ($http_user_agent ~* "yandex") { return 403; }
    - if ($http_user_agent ~* "ezooms") { return 403; }
    - if ($http_user_agent ~* "yahoo") { return 403; }
    - if ($http_user_agent ~* "webmeup-crawler") { return 403; }
    - if ($http_user_agent ~* "semrush") { return 403; }
    - if ($http_user_agent ~* "mj12bot") { return 403; }
    - if ($http_user_agent ~* "dotbot") { return 403; }
    - if ($http_user_agent ~* "360spider") { return 403; }
    - if ($http_user_agent ~* "pagefreezer") { return 403; }
    - if ($http_user_agent ~* "Dorkbot") { return 403; }
    - if ($http_user_agent ~* "semanticscholar") { return 403; }
    - if ($http_user_agent ~* "aspiegel") { return 403; }
