---

- name: "Create the users"
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    host: "{{ item.host | default('localhost') }}"
    column_case_sensitive: true
    state: "present"
    login_unix_socket: "{{ mariadb_socket }}"
  loop: "{{ mariadb_users }}"
  no_log: true
