---

# PLEASE NOTE THAT THE PASSWORD VALUES USED HERE ARE NOT SAFE

#
# atom role
#

atom_path: "/usr/share/nginx/atom"
atom_repository_url: "https://github.com/artefactual/atom.git"
atom_repository_version: "qa/2.5.x"
atom_config_db_hostname: "127.0.0.1"
atom_config_db_name: "atom"
atom_config_db_username: "atom-user"
atom_config_db_password: "ATOMPASSWORD"
atom_config_db_port: "3306"
atom_es_host: "127.0.0.1"
atom_es_port: "9200"
atom_es_config_version: "2.5"
atom_mysql_user_name: "atom-user"
atom_mysql_user_pass: "ATOMPASSWORD"
atom_mysql_user_priv: "atom.*:ALL,GRANT"
atom_mysql_user_host: "%"

#
# nginx role
#

nginx_configs:
  atom_backend:
    - upstream atom {
        server unix:/var/run/php-fpm.atom.sock;
      }

nginx_sites:
  atom:
    - listen 80
    - set $atom_path {{ atom_path }}
    - root $atom_path
    - server_name _
    - client_max_body_size 72M
    - location / { try_files $uri /index.php?$args; }
    - location ~ /\. {
        deny all;
        return 404;
      }
    - location ~* (\.yml|\.ini|\.tmpl)$ {
        deny all;
        return 404;
      }
    - location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
        return 404;
      }
    - location ~* /uploads/r/(.*)/conf/ { }
    - location ~* ^/uploads/r/(.*)$ {
        include /etc/nginx/fastcgi_params;
        set $index /index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$index;
        fastcgi_param SCRIPT_NAME $index;
        fastcgi_pass atom;
      }
    - location ~ ^/private/(.*)$ {
        internal;
        alias $atom_path/$1;
      }
    - location ~ ^/(index|qubit_dev)\.php(/|$) {
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass atom;
      }
    - location ~* \.php$ {
        deny all;
        return 404;
      }

# elasticsearch role

elasticsearch_version: "5.6.0"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
elasticsearch_heap_size: "1g"
elasticsearch_max_open_files: "65535"
elasticsearch_timezone: "UTC"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
#elasticsearch_thread_pools:
#  - "thread_pool.write.size: 2"
#  - "thread_pool.write.queue_size: 1000"
elasticsearch_network_http_max_content_lengtht: 1024mb
elasticsearch_discovery_zen_ping_multicast_enabled: "false"
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_network_host: "127.0.0.1"

#
# percona role
#

mysql_databases:
  - name: "atom"
    collation: "utf8_general_ci"
    encoding: "utf8"

mysql_users:
  - name: "{{ atom_mysql_user_name }}"
    pass: "{{ atom_mysql_user_pass }}"
    priv: "{{ atom_mysql_user_priv }}"
    host: "{{ atom_mysql_user_host }}"

mysql_root_password: "MYSQLROOTPASSWORD"
mysql_bind_address: "0.0.0.0"
