---
- hosts:
   - all

  pre_tasks:

    - name: "Remove old database"
      mysql_db:
        name: "{{ atom_config_db_name }}"
        login_user: "{{ atom_config_db_username }}"
        login_password: "{{ atom_config_db_password }}"
        login_host: "{{ atom_config_db_hostname }}"
        state: "absent"
        config_file: "/dev/null"
      ignore_errors: "yes"
      when: atom_install_sampledata|bool
      tags:
        - "atom-sampledata"


  roles:

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.acmetool"
      become: "yes"
      when:
        - acmetool_want is defined
      tags:
        - "acmetool"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "geerlingguy.composer"
      become: "yes"
      tags:
        - "composer"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"

    - role: "artefactual.atom.sampledata-2.6"
      become: "yes"
      tags:
        - "atom-sampledata"
      when: atom_install_sampledata|bool

