#!/usr/bin/env bash

set -euo pipefail

am_url=${AM_URL:-http://localhost:8000}
ss_url=${SS_URL:-http://localhost:8001}
am_api_key=${AM_API_KEY:-this_is_the_am_api_key}
ss_api_key=${SS_API_KEY:-this_is_the_ss_api_key}

echo "Checking the Archivematica API"
curl \
    --fail-with-body \
    --silent \
    --show-error \
    --header "Authorization: ApiKey admin:${am_api_key}" \
    --header 'Content-Type: application/json' \
    "${am_url}/api/processing-configuration/" \
    | jq --exit-status \
        '.processing_configurations == ["automated", "default"]' >/dev/null

echo "Checking the Storage Service API"
curl \
    --fail-with-body \
    --silent \
    --show-error \
    --header "Authorization: ApiKey admin:${ss_api_key}" \
    --header 'Content-Type: application/json' \
    "${ss_url}/api/v2/pipeline/" \
    | jq --exit-status '.meta.total_count == 1' >/dev/null
