---
- hosts: am-ppa-local
  gather_facts: true
  roles:
    - { role: "artefactual.elasticsearch", tags: ["elasticsearch"], sudo: yes }
    - { role: "artefactual.archivematica-pkg", tags: ["archivematica-pkg"], sudo: yes }

  vars:
    ppa:
      - 'archivematica/1.4'
    elasticsearch_version: "1.4.5"
    elasticsearch_timezone: "UTC"
