---
- hosts: "am-local-centos7"

  pre_tasks:

    - fail:
      msg: "This playbook is temporarily disabled, see https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/25 for more details. Uncomment this task if you want to test."

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"

    - name: "Install some python packages"
      become: "yes"
      yum:
         name: "{{ item }}"
         state: "present"
      with_items:
        - libsemanage-python
        - policycoreutils-python
        - MySQL-python

    - name: "Set SELinux to Permissive"
      command: "setenforce Permissive"      
      become: "yes"

    - name: "Enable epel repository"
      yum:
        name: "epel-release"
        state: "latest"
      become: "yes"

    - name: "Install mariadb-server"
      yum:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - "mariadb-server"
      become: "yes"

    - name: "Enable and start mariadb"   
      service:
        name: "{{ item }}"
        state: "started"
        enabled: "yes"
      with_items:
        - "mariadb"
      become: "yes"

    - name: "Make sure the MySQL databases are present"
      mysql_db:
        name: "{{ item.name }}"
        collation: "{{ item.collation | default('utf8_general_ci') }}"
        encoding: "{{ item.encoding | default('utf8') }}"
        state: "present"
      with_items: "{{ mysql_databases }}"
      become: "yes"

    - name: "Make sure the MySQL users are present"
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ item.pass | default('pass') }}"
        priv: "{{ item.priv | default('*.*:ALL') }}"
        state: "present"
        host: "{{ item.host | default('localhost') }}"
      with_items: "{{ mysql_users }}"
      become: "yes"

  roles:
    - { role: "artefactual.clamav", tags: ["clamav"], become: "yes" }
    - { role: "artefactual.gearman", tags: ["gearman"], become: "yes" }
    - { role: "jdauphant.nginx", tags: ["nginx"], become: "yes" }
    - { role: "artefactual.archivematica-src", tags: ["archivematica-src"], become: "yes" }

  tasks:
    - name: "change home dir perms (to make transfer source visible)"
      command: "chmod 755 $HOME" 
      tags: "homeperms"
      become: "no"

