---
- hosts: "am-local-centos7"

  pre_tasks:

    - fail:
      msg: "This playbook is temporarily disabled, see https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/25 for more details. Uncomment this task if you want to test."

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"


    - name: "Install SELinux related python packages"
      become: "yes"
      yum:
         name: "{{ item }}"
         state: "present"
      with_items:
        - libsemanage-python
        - policycoreutils-python

    - name: "Set SELinux to Permissive"
      command: "setenforce Permissive"
      become: "yes"

  roles:
    - { role: "artefactual.percona", tags: ["percona"], become: "yes" }
    - { role: "artefactual.clamav", tags: ["clamav"], become: "yes" }
    - { role: "artefactual.gearman", tags: ["gearman"], become: "yes" }
    - { role: "artefactual.nginx", tags: ["nginx"], become: "yes" }
    - { role: "artefactual.archivematica-src", tags: ["archivematica-src"], become: "yes" }

  tasks:
    - name: "change home dir perms (to make transfer source visible)"
      command: "chmod 755 $HOME"
      tags: "homeperms"
      become: "no"

