---
- hosts: "am-local-centos7"

  pre_tasks:

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"

    - name: "Install SELinux related python packages"
      become: "yes"
      yum:
         name: "{{ item }}"
         state: "present"
      with_items:
        - libsemanage-python
        - policycoreutils-python

    - name: "SELinux: Allow nginx connections to Gunicorn"
      become: "yes"
      seboolean:
        name: "httpd_can_network_connect"
        state: "yes"
        persistent: "yes"
      when: ansible_selinux.status == "enabled"

    - name: "SELinux: Allow nginx to connect to MySQL"
      become: "yes"
      seboolean:
        name: "httpd_can_network_connect_db"
        state: "yes"
        persistent: "yes"
      when: ansible_selinux.status == "enabled"

    - name: "SELinux: Allow nginx to change system limits"
      become: "yes"
      seboolean:
        name: "httpd_setrlimit"
        state: "yes"
        persistent: "yes"
      when: ansible_selinux.status == "enabled"

    - name: "SELinux: Allow nginx to use ports 8000 and 8001"
      become: "yes"
      seport:
        ports: "8000,8001"
        proto: "tcp"
        setype: "http_port_t"
        state: "present"
      when: ansible_selinux.status == "enabled"

  roles:
    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"
      when: "archivematica_src_search_enabled|bool"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.clamav"
      become: "yes"
      tags:
        - "clamav"

    - role: "artefactual.archivematica-src"
      become: "yes"
      tags:
        - "archivematica-src"

  tasks:
    - name: "change home dir perms (to make transfer source visible)"
      command: "chmod 755 $HOME" 
      tags: "homeperms"
      become: "no"

