---
- hosts: "am-local-centos7"

  pre_tasks:

    - include_vars: "vars-singlenode-1.12.yml"
      tags:
        - "always"

  roles:

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"
      when: "archivematica_src_search_enabled|bool"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.clamav"
      become: "yes"
      tags:
        - "clamav"

    - role: "artefactual.archivematica-src"
      become: "yes"
      tags:
        - "archivematica-src"
