# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   # ssh config
   config.ssh.username = "centos"
   config.ssh.private_key_path = "~/.ssh/id_rsa_artefactual"

   # openstack config
   config.vm.provider :openstack do |os, ov|
    os.server_name                      = 'vagrant_centos'
    os.openstack_auth_url               = ENV['OS_AUTH_URL']
    os.tenant_name                      = ENV['OS_TENANT_NAME']
    os.username                         = ENV['OS_USERNAME']
    os.password                         = ENV['OS_PASSWORD']
    os.region                           = ENV['OS_REGION_NAME']
    os.flavor                           = "b2-7"
    os.image                            = "Centos 7"
    os.keypair_name                        = "scollazo"
    ov.nfs.functional = false
   end


   # Ansible provisioning
   config.vm.provision :ansible do |ansible|
    ansible.playbook = "./singlenode.yml"
    ansible.host_key_checking = false
    ansible.extra_vars = {
      "archivematica_src_dir" => "/vagrant/src",
      "archivematica_src_environment_type" => "development",
    }
    #ansible.raw_arguments = ENV['ANSIBLE_ARGS']
    # accept multiple arguments, separated by colons
    ansible.raw_arguments = ENV['ANSIBLE_ARGS'].to_s.split(':')
  end
end
