---

# archivematica-src role

archivematica_src_install_devtools: "no"
archivematica_src_am_version: "stable/1.7.x"
archivematica_src_ss_version: "stable/0.11.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "yes"

# reset setup vars, commented out here, uncomment if needed
#archivematica_src_reset_am_all: "true"
#archivematica_src_reset_ss_db: "true"

# elasticsearch role, general settings 
# (instance specific settings are in the playbook )
es_scripts: false
es_templates: false
es_version_lock: false
es_heap_size: 348m
es_major_version: "1.7"
es_version: "1.7.6"
es_start_service: true
es_java_install: true
update_java: true
es_restart_on_change: true
es_allow_downgrades: false
es_enable_xpack: false
es_xpack_features: []
