---

# archivematica-src role

archivematica_src_install_devtools: "no"
archivematica_src_am_version: "stable/1.8.x"
archivematica_src_ss_version: "stable/0.13.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
archivematica_src_am_multi_venvs: "yes"

# reset setup vars, commented out here, uncomment if needed
#archivematica_src_reset_am_all: "true"
#archivematica_src_reset_ss_db: "true"

# elasticsearch role, general settings 
# (instance specific settings are in the playbook )
es_scripts: false
es_templates: false
es_version_lock: false
es_heap_size: 348m
es_major_version: "1.7"
es_version: "1.7.6"
es_start_service: true
es_java_install: true
update_java: true
es_restart_on_change: true
es_allow_downgrades: false
es_enable_xpack: false
es_xpack_features: []

# Percona variables
mysql_databases:
 - name: "{{ archivematica_src_am_db_name }}"
   collation: "utf8_general_ci"
   encoding: "utf8"
mysql_users:
 - name: "{{ archivematica_src_am_db_user }}"
   pass: "{{ archivematica_src_am_db_password }}"
   priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
   host: "{{ archivematica_src_am_db_host }}"
mysql_root_password: "ChangeMe!"

#AM configure vars

archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
archivematica_src_configure_ss_user: "admin"
archivematica_src_configure_ss_password: "archivematica"
archivematica_src_configure_ss_api_key: "this_is_the_ss_api_key"
archivematica_src_configure_ss_url: "http://192.168.168.197:8000"
archivematica_src_configure_ss_email: "admin@example.com"
archivematica_src_configure_am_user: "admin"
archivematica_src_configure_am_password: "archivematica"
archivematica_src_configure_am_email: "admin@example.com"
archivematica_src_configure_am_api_key: "this_is_the_am_api_key"
archivematica_src_configure_am_site_url: "http://192.168.168.197"
