---
- hosts: "binder-local"

  pre_tasks:

    - include_vars: "vars-singlenode-qa.yml"
      tags:
        - "always"

    - name: "Installing PPA for Java 8"
      apt_repository:
        repo: "ppa:openjdk-r/ppa"
      become: "yes"
      tags:
        - "always"

  roles:

    - role: "geerlingguy.java"
      become: "yes"
      tags:
        - "java"

    - role: "elastic.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"
