---
- hosts: "atom-local"

  pre_tasks:

    - include_vars: "vars-singlenode-qa.yml"
      tags:
        - "always"

    - name: "Upgrade all system packages"
      become: "yes"
      apt:
        name: "*"
        cache_valid_time: 3600
        state: latest
        update_cache: true
      tags:
        - "system-upgrade"

  roles:

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"
