name: "Archivematica Upgrade Test"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
    paths:
      - ".github/workflows/archivematica-upgrade.yml"
      - ".github/actions/setup-podman-test/**"
      - "playbooks/archivematica-noble/**"
      - "tests/archivematica-upgrade/**"
      - "tests/common/**"
      - "!tests/archivematica-upgrade/README.md"
      - "!tests/common/README.md"
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/archivematica-upgrade.yml"
      - ".github/actions/setup-podman-test/**"
      - "playbooks/archivematica-noble/**"
      - "tests/archivematica-upgrade/**"
      - "tests/common/**"
      - "!tests/archivematica-upgrade/README.md"
      - "!tests/common/README.md"
jobs:
  test:
    name: "Archivematica upgrade test"
    runs-on: "ubuntu-24.04"
    env:
      python_version: "3.12"
    steps:
      - name: "Check out the code"
        uses: "actions/checkout@v4"
      - name: "Set up the Podman test"
        uses: "./.github/actions/setup-podman-test"
        with:
          test-directory: "tests/archivematica-upgrade"
          python-version: "${{ env.python_version }}"
          cache-key-suffix: "archivematica-upgrade"
      - name: "Install the stable version of Archivematica"
        working-directory: "${{ github.workspace }}/tests/archivematica-upgrade"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_REMOTE_PORT: 2222
        run: |
          ../common/prepare-ansible-roles \
              ../../playbooks/archivematica-noble/requirements.yml
          ansible-playbook -i localhost, playbook.yml \
              -u ubuntu \
              -e "am_version=1.18" \
              -e "archivematica_src_configure_am_site_url=http://archivematica" \
              -e "archivematica_src_configure_ss_url=http://archivematica:8000" \
              -v
      - name: "Get the Archivematica version"
        run: |
          curl \
              --silent \
              --dump-header - \
              --header 'Authorization: ApiKey admin:this_is_the_am_api_key' \
              --header 'Content-Type: application/json' \
              'http://localhost:8000/api/processing-configuration/' | grep X-Archivematica-Version
      - name: "Check Archivematica APIs"
        run: |
          tests/common/check-archivematica-apis
      - name: "Uninstall Elasticsearch 6.x"
        working-directory: "${{ github.workspace }}/tests/archivematica-upgrade"
        run: |
          podman-compose exec --user root archivematica bash -c "apt-get purge -y elasticsearch"
          podman-compose exec --user root archivematica bash -c "rm -rf /etc/elasticsearch/ /var/lib/elasticsearch /var/log/elasticsearch"
      - name: "Upgrade to the QA version of Archivematica"
        working-directory: "${{ github.workspace }}/tests/archivematica-upgrade"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_REMOTE_PORT: 2222
        run: |
          rm -rf roles
          ../common/prepare-ansible-roles \
              ../../playbooks/archivematica-noble/requirements-qa.yml
          ansible-playbook -i localhost, playbook.yml \
              -u ubuntu \
              -e "am_version=qa" \
              -e "archivematica_src_configure_am_site_url=http://archivematica" \
              -e "archivematica_src_configure_ss_url=http://archivematica:8000" \
              -e "elasticsearch_version=8.19.2" \
              -t "elasticsearch,archivematica-src" \
              -v
      - name: "Get the Archivematica version"
        run: |
          curl \
              --silent \
              --dump-header - \
              --header 'Authorization: ApiKey admin:this_is_the_am_api_key' \
              --header 'Content-Type: application/json' \
              'http://localhost:8000/api/processing-configuration/' | grep X-Archivematica-Version
      - name: "Check Archivematica APIs"
        run: |
          tests/common/check-archivematica-apis
