---
# PLEASE NOTE THAT THE PASSWORD VALUES USED HERE ARE NOT SAFE
atom_repository:
  url: "https://github.com/artefactual/atom.git"
  version: "qa/2.2.x"

atom_config_db_hostname: "192.168.168.193"
atom_config_db_name: "atom"
atom_config_db_username: "atom-user"
atom_config_db_password: "ATOMPASSWORD"
atom_config_db_port: 3306

atom_es_host: "192.168.168.193"
atom_es_port: 9200

atom_qtsword_enabled: true

#
# nginx
#

nginx_configs:
  atom_backend:
    - upstream atom_backend {
        server unix:/var/run/php5-fpm.atom.sock;
      }

nginx_sites:
  atom:
    - listen 80
    - root /usr/share/nginx/atom
    - server_name _
    - client_max_body_size 72M
    - location / { try_files $uri /index.php?$args; }
    - location ~ /\. { deny all; return 404; }
    - location ~* (\.yml|\.ini|\.tmpl)$ { deny all; return 404; }
    - location ~* /(?:uploads|files)/.*\.php$ { deny all; return 404; }
    - location ~ ^/(index|qubit_dev)\.php(/|$) {
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass atom_backend;
      }
    - location ~* \.php$ { deny all; return 404; }

#
# mysql/percona
#

mysql_databases:
  - name: "atom"
    collation: "utf8_general_ci"
    encoding: "utf8"

atom_mysql_user_name: "atom-user"
atom_mysql_user_pass: "ATOMPASSWORD"
atom_mysql_user_priv: "atom.*:ALL,GRANT"
atom_mysql_user_host: "%"

mysql_users:
    - name: "{{ atom_mysql_user_name }}"
      pass: "{{ atom_mysql_user_pass }}"
      priv: "{{ atom_mysql_user_priv }}"
      host: "{{ atom_mysql_user_host }}"


#  vars:
mysql_root_password: "MYSQLROOTPASSWORD"
mysql_bind_address: "0.0.0.0"

#
# elasticsearch
#

elasticsearch_timezone : "UTC"
